language: java
jdk:
  - openjdk19
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api-key:
    secure: RceEntsuwEt0kxdtWhHXTgL1t/h19aBJlxY5osKw8FluVjOwge8czu1pftkFQo6cSLVKdp9NLZCU38UO0e4wofILzW2irbvgAjUSfc6Xl6JVrggm9gjYY5NZD4UgtYLERD03/z2dufpD5XhQFm/But7AKN40XvzAJypnvHV3uSQ3/OmB+K0VNwrjKh4X1V3RyjGX8kMV9RURveNPnZnrY3tPNFLlog+XZoKWifzD7UPLZLx5dLa6jXIOckoAWJM7+Awz4VROo7j8zV30FYRG6NHIpYSUsKI5svyr5FQ2hOvZeE8+1uD5NP9WCmhwn1oM4S5Zb75MNt6+XMsvX7GCIOWdaL0qAOPdMXyPqUpU2h/KR1mS0uqwBTaR3Q/txnzreVcOyUpPFjrPmOjwKKK/5bVwmcTh/0vVyNplpiGFlTdO4ANqku9wCbP08zEC1YedYPNHYQiPfySEwdPU5XZEYdquYjcY8sF/CXuRwok3kHdyQvVG2NHWxuV8kzGXD0WyufEeKSvDX42huJtrMEQ0gZ20kWsCIkYz4S1MJG9ajo54Imq02OzFal2O/ZfMGrd5qJ4b1qvgdc8JL2Y9JPnzPlOFy61I1uZVAqjhhzNpp9znMLRXeotdN0JMPmSTdhXY5Mp87/pc4dcV7XU5nwCbv6Q1EmzkgZ+e5GFeUNi98pw=
  app: sign-tube
